name: Pull request from Main to Env Branches

on:
  push:
    branches:
      - main

jobs:
  pr-to-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Install Hub CLI
      run: |
        sudo snap install hub --classic

    - name: Create Pull Requests
      run: |
        for branch in $(git branch -r | grep 'origin/env/' | sed 's|origin/||'); do
          echo "Creating pull request from main to $branch"
          git checkout $branch
          hub pull-request -b $branch -h main -m "PR from Main to $branch"

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
