name: Automatic PR from main to env/prod

on:
  push:
    branches:
      - main

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install hub
        run: |
          sudo apt-get update
          sudo apt-get install hub

      - name: Set up Git
        run: |
          git config --global user.name 'syed'
          git config --global user.email 'syed.com'

      - name: Create PRs from main to env branches
        run: |
          branches=$(git branch -r | grep 'origin/env/')
          for branch in $branches; do
            hub pull-request -b "$branch" -h main -m "Automatic PR from main to $branch"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
