name: Pull request from Main to Env Branches

on:
  push:
    branches:
      - main

jobs:
  pr-to-env:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}

    - name: Create Pull Requests
      run: |
        git fetch origin
        for branch in $(git branch -r | grep 'origin/env/' | sed 's|origin/||'); do
          echo "Creating pull request for $branch"
          git checkout -b temp_branch origin/main
          git checkout $branch
          git merge temp_branch --no-edit
          git push origin $branch
          hub pull-request -b $branch -h origin/main -m "PR From Main into $branch"
          git checkout main
          git branch -D temp_branch
        done

    - name: Install Hub CLI
      run: |
        sudo snap install hub --classic

    env:
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
