name: Create PR for all branches on push to main

on:
  push:
    branches:
      - main

jobs:

  create-prs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Get all branches
      id: get-branches
      run: |
        branches=$(git for-each-ref --format='%(refname:short)' refs/heads)
        echo "::set-output name=branches::$branches"
        
    - name: Create PRs
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        for branch in ${{ steps.get-branches.outputs.branches }}
        do
          if [ "$branch" != "main" ]; then
            gh pr create --base main --head $branch --title "Merge $branch into main" --body "This PR merges the $branch branch into the main branch."
          fi
        done
