name: Pull request from Auto Main to qay branch

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pr-to-env:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.JOSYS_GITHUB_TOKEN }}

    - name: Install Hub CLI
      run: |
        sudo snap install hub --classic
 
    - name: Create Pull Request to env/test
      id: create_pr
      run: |
        git fetch origin
        branch="env/test"
        echo "Checking if a pull request already exists for $branch"
        existing_pr=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.JOSYS_GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?head=main&base=$branch")
        if [[ $(echo "$existing_pr" | jq -r ".[].head.ref") == "main" ]]; then
          echo "A pull request already exists from main to $branch. Skipping..."
        else
          echo "Creating pull request from main to $branch"
          hub pull-request -b $branch -h main -m "PR from main to $branch"
        fi
        echo "::set-output name=pr_url::$(hub pr list -b $branch -h main -f '%U')"
 
    - name: Transfer Labels
      if: steps.create_pr.outputs.pr_url != ''
      run: |
        pr_url=${{ steps.create_pr.outputs.pr_url }}
        pr_number=$(echo $pr_url | awk -F/ '{print $NF}')
        merged_pr_number=${{ github.event.pull_request.number }}
        
        # Get labels from the merged PR
        labels=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.JOSYS_GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$merged_pr_number/labels" | jq -r '.[].name')
        
        # Apply labels to the new PR
        for label in $labels; do
          curl -s -X POST -H "Authorization: Bearer ${{ secrets.JOSYS_GITHUB_TOKEN }}" -H "Content-Type: application/json" \
            --data "{\"labels\":[\"$label\"]}" "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$pr_number/labels"
        done
 
    env:
      GITHUB_TOKEN: ${{ secrets.JOSYS_GITHUB_TOKEN }}
