# name: "Terraform action"
# on:
#   pull_request:
#     types: [labeled]
#     branches:
#       - 'env/**'
#   push:
#     branches:
#       - 'env/**'
   
# jobs:
#   deploy:
#     if: contains(github.event.pull_request.labels.*.name, 'terraform-plan') 
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#     steps:
#       - name: Determine TARGET_BRANCH
#         id: determine_target_branch
#         run: |
#           pwd

#       - name: Merge PR
#         run: |
#           curl -s -H "Authorization: token ${{ secrets.JOSYS_GITHUB_TOKEN }}" \
#           -X PUT \
#           -d '{"merge_method":"merge"}' \
#           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
