name: "Terraform action"
on:
  pull_request:
    types: [labeled]
    branches:
      - 'env/**'
  push:
    branches:
      - 'env/**'
   
jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'terraform-plan') 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Determine TARGET_BRANCH
        id: determine_target_branch
        run: |
          pwd
      - name: Merge Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.JOSYS_GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Merging pull request #$PR_NUMBER"
          gh pr merge $PR_NUMBER --merge --admin
