name: "Terraform action"
on:
  pull_request:
    types: [labeled]
    branches:
      - 'env/**'
  push:
    branches:
      - 'env/**'
   
jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'terraform-plan') 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Determine TARGET_BRANCH
        id: determine_target_branch
        run: |
          pwd
          
      - name: Merge PR
        if: github.event.action == 'opened'
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;
            await github.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              merge_method: 'merge'
            });
